### PR TITLE
Enhancement : Added a github icon and attached the link of repo to it.

### LINKED ISSUE #1: Attaching GitHub Repo in the website using React icon
Attach a GitHub icon which will redirect to GitHub. Use [React icon](https://react-icons.github.io/react-icons/search/#q=github).

### PR DESCRIPTION
**Pull request by Dharsan15**
### Related Issue(s)

- Fix #1 

### Description

Added a github icon (using react icons) to the website which will redirect the user to the github repo of the project 

### Changes Made

-  created a new file with a navbar component [Navbar.component.jsx]
-  updated  App.jsx 
-  updated package.json & package.lock.json

### Screenshots (if applicable)

Screenshot (17)

### Checklist

-  Code follows the project's style and conventions.
- Code has been tested thoroughly, and all tests pass successfully.
- Documentation has been updated to reflect any relevant changes.
-  All new and modified code is adequately commented for clarity.
-  Pull request title follows the specified format: [Feature/Enhancement/Bug Fix]: Brief description of the change.

### Additional Notes

Review the PR and share your feedback on any further improvements....

### CODE REVIEW

**Comment by swrno** [comment]
Great work! But can you please add `Swarnendu0123/http-request-inspector` at the left of the GitHub icon, with a light grey background. And make the icon at the right of the screen.

**Comment by Dharsan15** [comment]
sure

**Comment by Dharsan15** [comment]
Screenshot

###  Is it okay

**Comment by swrno** [comment]
@Dharsan15 its looking okay for now. Thanks for your contribution.

**Comment by Dharsan15** [comment]
Thank you @Swarnendu0123 and looking forward to contribute more to the project ....

**Comment by swrno** [comment]
> Screenshot
> 
> ###  Is it okay 

Please raise another PR for these changes, so that I can merge it.

**Comment by Dharsan15** [comment]
yeah !

**Pull request merged**
